from __future__ import annotations

REGISTRY_BY_OBJECT_TYPE: dict[str, str] = {
    "PROJECT": "PROJECT_REGISTRY",
    "SOURCE": "RESEARCH_REGISTRY", "CLAIM": "RESEARCH_REGISTRY", "EVIDENCE": "RESEARCH_REGISTRY",
    "CONTRADICTION": "RESEARCH_REGISTRY", "RESEARCH_GAP": "RESEARCH_REGISTRY",
    "SEARCH": "ASSET_REGISTRY", "SEARCH_RESULT": "ASSET_REGISTRY", "ASSET": "ASSET_REGISTRY", "SEGMENT": "ASSET_REGISTRY",
    "ACT": "NARRATIVE_REGISTRY", "SCENE": "NARRATIVE_REGISTRY", "NARRATION_BEAT": "NARRATIVE_REGISTRY",
    "VOICE_PROFILE": "VOICE_REGISTRY", "VOICE_BLOCK": "VOICE_REGISTRY",
    "DESIGN_DNA": "DESIGN_REGISTRY",
    "SHOT": "PLANNING_REGISTRY", "LAYER": "PLANNING_REGISTRY", "CUE": "PLANNING_REGISTRY",
    "APPROVAL": "REVIEW_REGISTRY", "EDIT_REQUEST": "REVIEW_REGISTRY", "REVISION": "REVIEW_REGISTRY",
    "RENDER_JOB": "RENDER_REGISTRY", "RENDER_MANIFEST": "RENDER_REGISTRY",
    "QA_ISSUE": "QA_REGISTRY", "QA_REPORT": "QA_REGISTRY",
    "CHECKPOINT": "CHECKPOINT_REGISTRY", "OPERATION": "OPERATION_REGISTRY", "INCIDENT": "INCIDENT_REGISTRY", "RELEASE": "RELEASE_REGISTRY",
}

ID_PREFIX_BY_OBJECT_TYPE: dict[str, str] = {
    "PROJECT": "PROJECT_", "ACT": "ACT_", "SCENE": "SCN_", "NARRATION_BEAT": "NB_",
    "SOURCE": "SRC_", "CLAIM": "CLM_", "EVIDENCE": "EVD_", "CONTRADICTION": "CTR_", "RESEARCH_GAP": "GAP_",
    "SEARCH": "SRCH_", "SEARCH_RESULT": "SR_", "ASSET": "AST_", "SEGMENT": "SEG_",
    "VOICE_PROFILE": "VP_", "VOICE_BLOCK": "VB_", "DESIGN_DNA": "DNA_",
    "SHOT": "SHT_", "LAYER": "LYR_", "CUE": "CUE_",
    "APPROVAL": "APR_", "EDIT_REQUEST": "EDR_", "REVISION": "REV_",
    "QA_ISSUE": "QAI_", "QA_REPORT": "QAR_", "RENDER_JOB": "RJ_", "RENDER_MANIFEST": "RM_",
    "CHECKPOINT": "CP_", "OPERATION": "OP_", "INCIDENT": "INC_", "RELEASE": "REL_",
}

SYSTEM_MANAGED_FIELDS = {
    "schema_header", "id", "object_type", "version", "supersedes", "status", "lock_state",
    "created_at", "updated_at", "dependencies", "stale", "approval_summary",
}
DERIVED_REFRESH_FIELDS = {"status", "lock_state", "dependencies", "stale", "approval_summary"}
PROMOTION_BLOCKING_STATUSES = {"STALE", "BLOCKED", "ARCHIVED", "REJECTED"}
PROMOTION_ALLOWED_APPROVAL_STATES = {"NOT_REQUIRED", "SATISFIED"}
PROJECT_STATES = (
    "BOOTSTRAPPED", "RESEARCH_INTAKE", "RESEARCH_AUDITED", "ROUGH_NARRATIVE_READY",
    "VISUAL_REQUIREMENTS_READY", "ASSET_RECON", "ASSET_CATALOG_READY", "VISUAL_COVERAGE_READY",
    "SCRIPT_READY", "TTS_READY", "VOICE_LOCKED", "DESIGN_DNA_APPROVED", "SCENE_PLAN_READY",
    "SHOT_PLAN_READY", "HTML_REVIEW", "HTML_APPROVED", "PRODUCTION_RENDER", "SHOT_QA_PASSED",
    "SCENE_QA_PASSED", "FULL_FILM_QA_PASSED", "DELIVERY_READY", "PROJECT_COMPLETED",
)

STANDARD_REGISTRY_IDS = tuple(dict.fromkeys(REGISTRY_BY_OBJECT_TYPE.values()))
